version: 0.2

phases:
  install:
    commands:
      - echo Installing NodeJS...
      - apt install  nodejs
      - echo Node Installed version...
      - node -v
      
      #install yarn?
      - echo Installing Node package manager
      - apt install npm
  pre_build:
    commands:
      #install dependencies
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
